# Generated by Django 4.2 on 2024-06-25 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Число')),
            ],
            options={
                'verbose_name': 'число',
                'verbose_name_plural': 'числа',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, unique=True, verbose_name='Язык')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'язык',
                'verbose_name_plural': 'языки',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ник телеграм')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('family_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона')),
                ('addresses', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Адреса')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=4096, null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('start_date', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('end_date', models.DateField(verbose_name='Дата окончания срока действия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер паспорта')),
                ('passport_photo_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='TG id паспорта')),
                ('curr_input', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Текущий ввод')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.language', verbose_name='Язык')),
                ('passport_photo_user', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото паспорта')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='TGText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, verbose_name='Идентификатор')),
                ('text', models.TextField(max_length=4096, verbose_name='Текст')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='core.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текстовое наполнение',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=100, unique=True, verbose_name='Маршрут')),
                ('days', models.ManyToManyField(blank=True, to='core.day', verbose_name='Числа')),
            ],
            options={
                'verbose_name': 'маршрут',
                'verbose_name_plural': 'маршруты',
            },
        ),
        migrations.CreateModel(
            name='ParcelVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вариант посылки')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_variations', to='core.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'вариант посылки',
                'verbose_name_plural': 'Варианты посылки',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_receiver', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО получателя')),
                ('phone_receiver', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона получателя')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона отправителя')),
                ('address', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Адрес отправителя')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=4096, null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('start_date', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('end_date', models.DateField(verbose_name='Дата окончания срока действия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер паспорта')),
                ('passport_photo_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='TG id паспорта')),
                ('complete', models.BooleanField(default=False, verbose_name='Заявка подтверждена')),
                ('passport_photo_parcel', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото паспорта')),
                ('variation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='core.parcelvariation', verbose_name='Вариант посылки')),
            ],
            options={
                'verbose_name': 'посылка',
                'verbose_name_plural': 'посылки',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('oneway', 'В одну сторону'), ('roundtrip', 'Туда-обратно')], max_length=15, null=True, verbose_name='Тип перелета')),
                ('departure_date', models.DateField(verbose_name='Дата отлета')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='Дата прилета')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('family_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('address', models.CharField(blank=True, max_length=4096, null=True, verbose_name='Адрес')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=4096, null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('start_date', models.DateField(verbose_name='Дата выдачи паспорта')),
                ('end_date', models.DateField(verbose_name='Дата окончания срока действия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер паспорта')),
                ('passport_photo_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='TG id паспорта')),
                ('complete', models.BooleanField(default=False, verbose_name='Заявка подтверждена')),
                ('passport_photo_flight', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото паспорта')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='core.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'перелет',
                'verbose_name_plural': 'перелеты',
            },
        ),
    ]
