# Generated by Django 4.2 on 2024-06-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_day_options_alter_parcelvariation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='complete',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Заявка подтверждена'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='complete',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Заявка подтверждена'),
        ),
    ]
