# Generated by Django 4.2 on 2024-06-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_flight_complete_alter_parcel_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='items_list',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Предметы в посылке'),
        ),
    ]
