# Generated by Django 4.2 on 2024-06-29 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_route_options_route_my_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='opposite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_opposite', to='core.route'),
        ),
    ]
