# Generated by Django 4.2 on 2024-06-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_route_opposite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отлета'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания срока действия паспорта'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания срока действия паспорта'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания срока действия паспорта'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
    ]
