# Generated by Django 4.2 on 2024-06-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_flight_birth_date_alter_flight_departure_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='finished',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Заявка обработана'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='finished',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Заявка обработана'),
        ),
    ]
