# Generated by Django 4.2 on 2024-07-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_flight_finished_parcel_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='confirmed',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Заявка подтверждена менеджером'),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.FloatField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='confirmed',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Заявка подтверждена менеджером'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='price',
            field=models.FloatField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='complete',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Заявка подтверждена пользователем'),
        ),
    ]
