# Generated by Django 4.2 on 2024-07-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_flight_confirmed_flight_price_parcel_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='complete',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Заявка подтверждена пользователем'),
        ),
    ]
