# Generated by Django 4.2 on 2024-07-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_parcel_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='finished',
        ),
    ]
