# Generated by Django 4.2 on 2024-07-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_flight_circuit_id_parcel_circuit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Отобразится на кнопке', max_length=100, verbose_name='Название тарифа')),
                ('description', models.TextField(verbose_name='Описание тарифа')),
                ('price', models.FloatField(verbose_name='Ежемесячная стоимость')),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'вариант посылки',
                'verbose_name_plural': 'Варианты посылки',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='UsersSim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_phone', models.CharField(max_length=25, unique=True, verbose_name='Номер телефона')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата приобретения')),
                ('next_payment', models.DateField(verbose_name='Дата следующего платежа')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='Планируемая дата оплаты')),
                ('debt', models.FloatField(help_text='Отрицательная, при оплате наперед', verbose_name='Задолженность')),
                ('ready_to_pay', models.BooleanField(default=False)),
                ('circuit_id', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Circuit id')),
                ('fare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sims', to='core.simfare', verbose_name='Тариф')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_cards', to='core.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'вариант посылки',
                'verbose_name_plural': 'Варианты посылки',
                'ordering': ('-created_at',),
            },
        ),
    ]
