# Generated by Django 4.2 on 2024-07-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_simfare_options_alter_userssim_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userssim',
            name='circuit_id_collect',
            field=models.CharField(blank=True, help_text='После получения денег - удалить.', max_length=250, null=True, unique=True, verbose_name='Circuit id (collect money)'),
        ),
        migrations.AlterField(
            model_name='userssim',
            name='circuit_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Circuit id (delivery_sim)'),
        ),
    ]
