# Generated by Django 4.2 on 2024-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userssim_circuit_id_collect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userssim',
            name='pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата оплаты'),
        ),
    ]
