# Generated by Django 4.2 on 2024-07-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('core', '0019_alter_userssim_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userssim',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Последний водитель, вносивший информацию через бота о переданных клиентом деньгах', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_cards', to='drivers.driver', verbose_name='Водитель'),
        ),
    ]
