# Generated by Django 4.2 on 2024-07-15 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userssim_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст уведомления')),
                ('notify_now', models.BooleanField(default=True, verbose_name='Уведомить сейчас')),
                ('notify_time', models.DateTimeField(blank=True, help_text='Игнорируется, если активно поле "уведомить сейчас".', null=True, verbose_name='Время уведомления')),
                ('notified', models.BooleanField(blank=True, default=None, null=True, verbose_name='Уведомлен')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.tguser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'уведомление пользователя',
                'verbose_name_plural': 'уведомления пользователей',
                'ordering': ('-notify_time',),
            },
        ),
    ]
