# Generated by Django 4.2 on 2024-07-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_time',
            field=models.DateTimeField(blank=True, help_text='Указывается в UTC (-3 от МСК). Игнорируется, если активно поле "уведомить сейчас".', null=True, verbose_name='Время уведомления'),
        ),
    ]
