# Generated by Django 4.2 on 2024-07-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_userssim_icount_id_alter_flight_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Пользователь активен?'),
        ),
    ]
