# Generated by Django 4.2 on 2024-07-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_tguser_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldSim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='Телеграм id')),
                ('sim_phone', models.CharField(max_length=100, unique=True, verbose_name='Номер симкарты')),
                ('address', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Адрес')),
                ('name', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Имя')),
                ('family_name', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Фамилия')),
                ('debt', models.FloatField(verbose_name='Задолженность')),
                ('next_payment', models.DateField(verbose_name='Дата следующего платежа')),
                ('to_main_bot', models.BooleanField(default=False, verbose_name='Перенесена в основного бота?')),
                ('curr_input', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Текущий ввод')),
                ('fare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_sims', to='core.simfare', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'старая сим карта',
                'verbose_name_plural': 'старые сим карты',
            },
        ),
    ]
