# Generated by Django 4.2 on 2024-07-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_oldsim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldsim',
            name='curr_input',
        ),
        migrations.RemoveField(
            model_name='oldsim',
            name='family_name',
        ),
    ]
