# Generated by Django 4.2 on 2024-07-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_oldsim_curr_input_remove_oldsim_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldsim',
            name='icount_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userssim',
            name='debt',
            field=models.FloatField(help_text='Отрицательная, при оплате наперед.', verbose_name='Задолженность'),
        ),
    ]
