# Generated by Django 4.2 on 2024-07-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_oldsim_icount_id_alter_userssim_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userssim',
            name='is_old_sim',
            field=models.BooleanField(default=False, verbose_name='Старая симка?'),
        ),
    ]
