# Generated by Django 4.2 on 2024-08-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userssim_is_old_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='circuit_api',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='circuit_api',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
