# Generated by Django 4.2 on 2024-08-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_flight_circuit_api_parcel_circuit_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='userssim',
            name='circuit_api',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userssim',
            name='circuit_api_collect',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userssim',
            name='icount_api',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userssim',
            name='icount_api_collect',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userssim',
            name='icount_collect_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
