# Generated by Django 4.2 on 2024-09-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_improvednotification_linkbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='userssim',
            name='is_stopped',
            field=models.BooleanField(default=False, verbose_name='Приостановлен'),
        ),
    ]
