# Generated by Django 4.2 on 2024-10-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_apperror'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppError',
        ),
    ]
