# Generated by Django 4.2 on 2024-11-05 02:31

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_rus', models.CharField(max_length=256, verbose_name='Текст вопроса (русский)')),
                ('question_uzb', models.CharField(max_length=256, verbose_name='Текст вопроса (узбекский)')),
                ('answer_rus', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст ответа (русский)')),
                ('answer_uzb', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст ответа (узбекский)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'вопрос-ответ',
                'verbose_name_plural': 'FAQ',
                'ordering': ('order',),
            },
        ),
    ]
