# Generated by Django 4.2 on 2024-11-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rate',
            field=models.BooleanField(default=False, verbose_name='Показать курс?'),
        ),
    ]
