# Generated by Django 4.2 on 2024-12-06 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_question_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='language',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='users', to='core.language', verbose_name='Язык'),
        ),
    ]
