# Generated by Django 4.2 on 2024-12-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_tguser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='thread_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Thread ID'),
        ),
    ]
