# Generated by Django 4.2 on 2024-07-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('telegram_id', models.CharField(max_length=50, unique=True, verbose_name='Telegram id')),
                ('circuit_id', models.CharField(max_length=100, unique=True, verbose_name='Telegram id')),
                ('curr_input', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Текущий ввод')),
            ],
            options={
                'verbose_name': 'водитель',
                'verbose_name_plural': 'водители',
                'ordering': ('pk',),
            },
        ),
    ]
