# Generated by Django 4.2 on 2024-07-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='circuit_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Circuit id'),
        ),
    ]
