# Generated by Django 4.2 on 2024-08-28 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0031_userssim_circuit_api_userssim_circuit_api_collect_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Имя')),
                ('sim_phone', models.CharField(max_length=25, unique=True, verbose_name='Номер телефона')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата приобретения')),
                ('next_payment', models.DateField(verbose_name='Дата следующего платежа')),
                ('debt', models.FloatField(help_text='Отрицательная, при оплате наперед.', verbose_name='Задолженность')),
                ('icount_id', models.IntegerField(blank=True, default=None, null=True)),
                ('to_main_bot', models.BooleanField(default=False, verbose_name='Перенесена в основного бота?')),
                ('icount_api', models.BooleanField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_sims', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('fare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins_sims', to='core.simfare', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'сим карта',
                'verbose_name_plural': 'сим карты',
                'ordering': ('-created_at',),
            },
        ),
    ]
