# Generated by Django 4.2 on 2024-09-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcard',
            name='is_stopped',
            field=models.BooleanField(default=False, verbose_name='Приостановлен'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Имя'),
        ),
    ]
