# Generated by Django 4.2 on 2024-10-10 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_usermessage'),
        ('sim', '0003_alter_simcard_icount_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Дата отчета')),
                ('first_driver_ils', models.FloatField(default=0, verbose_name='Получено ₪ (первый водитель)')),
                ('first_driver_points', models.IntegerField(default=0, verbose_name='Кол-во адресов (первый водитель)')),
                ('second_driver_ils', models.FloatField(default=0, verbose_name='Получено ₪ (второй водитель)')),
                ('second_driver_points', models.IntegerField(default=0, verbose_name='Кол-во адресов (второй водитель)')),
                ('third_driver_ils', models.FloatField(default=0, verbose_name='Получено ₪ (третий водитель)')),
                ('third_driver_points', models.IntegerField(default=0, verbose_name='Кол-во адресов (третий водитель)')),
            ],
            options={
                'verbose_name': 'отчет',
                'verbose_name_plural': 'отчеты',
                'ordering': ('-report_date',),
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата приобретения')),
                ('amount', models.FloatField(blank=True, default=None, null=True, verbose_name='Сумма')),
                ('driver', models.CharField(choices=[('1', 'Первый водитель'), ('2', 'Второй водитель'), ('3', 'Третий водитель')], max_length=50, verbose_name='Водитель')),
                ('sim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to='core.userssim', verbose_name='Симкарта')),
            ],
            options={
                'verbose_name': 'сбор за симкарту',
                'verbose_name_plural': 'сборы за симкарты',
                'ordering': ('-created_at',),
            },
        ),
    ]
