# Generated by Django 4.2 on 2024-11-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0004_report_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='receipt',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка'),
        ),
    ]
