# Generated by Django 4.2 on 2025-02-20 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_cart_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элемент заказа', 'verbose_name_plural': 'Элементы заказов'},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'verbose_name': 'eдиница измерения', 'verbose_name_plural': 'eдиницы измерения'},
        ),
    ]
