# Generated by Django 4.2 on 2025-03-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_buyerprofile_balance_buyerprofile_referrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=255, verbose_name='Токен бота')),
                ('bot_name', models.CharField(max_length=255, verbose_name='Имя бота')),
                ('referral_percent', models.DecimalField(decimal_places=3, default=0, help_text='Укажите долю реферальных отчислений (0.01=1%)', max_digits=5, verbose_name='Доля реферальных отчислений')),
                ('orders_per_page', models.PositiveIntegerField(default=5, verbose_name='Количество заказов на странице')),
                ('help_chat', models.CharField(max_length=255, verbose_name='Чат поддержки')),
                ('web_app_url', models.CharField(max_length=255, verbose_name='URL веб-приложения')),
            ],
            options={
                'verbose_name': 'Настройки магазина',
                'verbose_name_plural': 'Настройки магазина',
            },
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='referral_percent',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Укажите долю реферальных отчислений (0.01=1%)', max_digits=5, verbose_name='Доля реферальных отчислений'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='referrals_count',
            field=models.IntegerField(default=0, verbose_name='Количество рефералов'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='thread_id',
            field=models.CharField(default=1, max_length=255, verbose_name='ID в Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('awaiting_payment', 'Ожидает оплаты'), ('awaiting_delivery', 'Ожидает доставки'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='created', max_length=256, verbose_name='Статус заказа'),
        ),
    ]
