# Generated by Django 4.2 on 2025-03-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_basesettings_buyerprofile_referral_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID в Telegram'),
        ),
    ]
