# Generated by Django 4.2 on 2025-03-05 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0009_alter_buyerprofile_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Топик id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
