# Generated by Django 4.2 on 2025-03-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_buyerprofile_thread_id_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен?'),
        ),
    ]
