# Generated by Django 4.2 on 2025-03-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('awaiting_delivery', 'Ожидает доставки'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='created', max_length=256, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category'),
            preserve_default=False,
        ),
    ]
