# Generated by Django 4.2 on 2025-03-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_status_alter_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Токен')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован?')),
            ],
            options={
                'verbose_name': 'Токен доступа',
                'verbose_name_plural': 'Токены доступа',
            },
        ),
    ]
