# Generated by Django 4.2 on 2025-03-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_buyerprofile_icount_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='circuit_success',
        ),
        migrations.AddField(
            model_name='order',
            name='icount_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=True, verbose_name='Оплачен?'),
        ),
    ]
