# Generated by Django 4.2 on 2025-03-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_order_circuit_success_order_icount_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='israel_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес в Израиле'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='israel_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон в Израиле'),
        ),
    ]
