# Generated by Django 4.2 on 2025-03-31 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0017_buyerprofile_israel_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('awaiting', 'Ожидает забора'), ('completed', 'Выполнен'), ('canceled', 'Отменен')], default='created', max_length=255, verbose_name='Статус')),
                ('circuit_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID circuit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на пополнение баланса',
                'verbose_name_plural': 'Запросы на пополнение баланса',
            },
        ),
    ]
