# Generated by Django 4.2 on 2025-03-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_topuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuprequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма'),
        ),
    ]
