# Generated by Django 4.2 on 2025-03-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_topuprequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.CharField(blank=True, choices=[('1', 'Первый водитель'), ('2', 'Второй водитель'), ('3', 'Третий водитель'), ('4', 'Четвертый водитель')], max_length=255, null=True, verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='driver',
            field=models.CharField(blank=True, choices=[('1', 'Первый водитель'), ('2', 'Второй водитель'), ('3', 'Третий водитель'), ('4', 'Четвертый водитель')], max_length=255, null=True, verbose_name='Водитель'),
        ),
    ]
