# Generated by Django 4.2 on 2025-03-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_order_driver_topuprequest_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='driver_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
