# Generated by Django 4.2 on 2024-07-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiver',
            options={'ordering': ('-updated_at',), 'verbose_name': 'получатель', 'verbose_name_plural': 'получатели'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name': 'получатель', 'verbose_name_plural': 'получатели'},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='deliveries',
        ),
        migrations.AddField(
            model_name='sender',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='senders', to='money_transfer.receiver', verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='receivers_addresses', to='money_transfer.address', verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='senders_addresses', to='money_transfer.address', verbose_name='Адреса'),
        ),
    ]
