# Generated by Django 4.2 on 2024-07-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0002_alter_receiver_options_alter_transfer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='valid',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Валидный заказ'),
        ),
    ]
