# Generated by Django 4.2 on 2024-07-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0004_delivery_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='valid_addresses',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Валидные адреса получателей'),
        ),
    ]
