# Generated by Django 4.2 on 2024-07-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0005_delivery_valid_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='valid_addresses',
        ),
    ]
