# Generated by Django 4.2 on 2024-07-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0006_remove_delivery_valid_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, verbose_name='Размер')),
                ('unit', models.IntegerField(choices=[(1, 'Проценты'), (2, 'Шекели')], verbose_name='Единицы измерения')),
                ('low_value', models.FloatField(default=0, verbose_name='От (в долларах)')),
                ('high_value', models.FloatField(default=0, verbose_name='До (в долларах)')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'комиссия',
                'verbose_name_plural': 'комиссии',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=10, unique=True, verbose_name='Валютная пара')),
                ('rate', models.FloatField(default=0, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
    ]
