# Generated by Django 4.2 on 2024-07-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0008_alter_commission_high_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='high_value',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='До (в долларах)'),
        ),
    ]
