# Generated by Django 4.2 on 2024-07-04 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0009_alter_commission_high_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=10, unique=True, verbose_name='Слаг')),
                ('text', models.CharField(max_length=200, unique=True, verbose_name='Описание статуса')),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'статусы',
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='money_transfer.status', verbose_name='Статус'),
        ),
    ]
