# Generated by Django 4.2 on 2024-07-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0010_status_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='circuit_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
