# Generated by Django 4.2 on 2024-07-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0012_alter_delivery_circuit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='total_usd',
            field=models.FloatField(default=0, help_text='Рассчитается автоматически', verbose_name='Итого в долларах'),
        ),
    ]
