# Generated by Django 4.2 on 2024-07-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0013_delivery_total_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='ils_amount',
        ),
    ]
