# Generated by Django 4.2 on 2024-07-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0014_remove_transfer_ils_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='commission',
            field=models.FloatField(default=0, help_text='Рассчитается автоматически', verbose_name='Комиссия (₪)'),
        ),
    ]
