# Generated by Django 4.2 on 2024-07-22 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_userssim_icount_id_alter_flight_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money_transfer', '0017_delivery_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='core.tguser', verbose_name='Пользователь tg'),
        ),
        migrations.AddField(
            model_name='sender',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='core.tguser', verbose_name='Пользователь tg'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
