# Generated by Django 4.2 on 2024-07-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_oldsim_icount_id_alter_userssim_debt'),
        ('money_transfer', '0018_receiver_user_sender_user_alter_delivery_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='core.tguser', verbose_name='Пользователь tg'),
        ),
        migrations.AlterField(
            model_name='sender',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='core.tguser', verbose_name='Пользователь tg'),
        ),
    ]
