# Generated by Django 4.2 on 2024-07-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0019_alter_receiver_user_alter_sender_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Номер телефона'),
        ),
    ]
