# Generated by Django 4.2 on 2024-07-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0020_alter_receiver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='pass_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Передано получателю'),
        ),
    ]
