# Generated by Django 4.2 on 2024-07-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0021_transfer_pass_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
