# Generated by Django 4.2 on 2024-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0023_alter_transfer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='rate',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Курс на момент перевода'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='credit',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='В кредит?'),
        ),
    ]
