# Generated by Django 4.2 on 2024-08-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0024_delivery_rate_transfer_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='circuit_api',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='gspread_api',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
