# Generated by Django 4.2 on 2024-08-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0025_delivery_circuit_api_delivery_gspread_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='curr_input',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Текущий ввод'),
        ),
    ]
