# Generated by Django 4.2 on 2024-09-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0028_alter_buyrate_options_alter_debitcredit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Дата отчета')),
                ('first_driver_usd', models.FloatField(default=0, verbose_name='Получено $ (первый водитель)')),
                ('first_driver_ils', models.FloatField(default=0, verbose_name='Получено ₪ (первый водитель)')),
                ('first_driver_commission', models.FloatField(default=0, verbose_name='Получено комиссии ₪ (первый водитель)')),
                ('first_driver_points', models.IntegerField(default=0, verbose_name='Кол-во адресов (первый водитель)')),
                ('second_driver_usd', models.FloatField(default=0, verbose_name='Получено $ (второй водитель)')),
                ('second_driver_ils', models.FloatField(default=0, verbose_name='Получено ₪ (второй водитель)')),
                ('second_driver_commission', models.FloatField(default=0, verbose_name='Получено комиссии ₪ (второй водитель)')),
                ('second_driver_points', models.IntegerField(default=0, verbose_name='Кол-во адресов (второй водитель)')),
                ('third_driver_usd', models.FloatField(default=0, verbose_name='Получено $ (третий водитель)')),
                ('third_driver_ils', models.FloatField(default=0, verbose_name='Получено ₪ (третий водитель)')),
                ('third_driver_commission', models.FloatField(default=0, verbose_name='Получено комиссии ₪ (третий водитель)')),
                ('third_driver_points', models.IntegerField(default=0, verbose_name='Кол-во адресов (третий водитель)')),
            ],
            options={
                'verbose_name': 'отчет',
                'verbose_name_plural': 'отчеты',
                'ordering': ('-report_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='debitcredit',
            options={'ordering': ('-date',), 'verbose_name': 'дебит-кредит', 'verbose_name_plural': 'дебит-кредит'},
        ),
    ]
