# Generated by Django 4.2 on 2025-02-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0031_delivery_approved_by_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='cancel_validation',
            field=models.BooleanField(default=False, verbose_name='Пропустить валидацию?'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='custom_commission',
            field=models.FloatField(blank=True, default=0, help_text='Перезапишет значение рассчитанной автоматически комиссии', verbose_name='Задать свою комиссию (₪)'),
        ),
    ]
