# Generated by Django 4.2 on 2025-02-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0032_delivery_cancel_validation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='custom_commission',
            field=models.FloatField(blank=True, default=0, verbose_name='Задать свою комиссию (₪)'),
        ),
    ]
