# Generated by Django 4.2 on 2025-02-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0033_alter_delivery_custom_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='received_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата получения'),
        ),
    ]
