# Generated by Django 4.2 on 2025-02-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_transfer', '0034_delivery_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='drivers_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий водителей'),
        ),
    ]
