# Generated by Django 4.2 on 2024-08-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='complete',
        ),
    ]
