# Generated by Django 4.2 on 2024-08-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='address',
            field=models.CharField(default='address', max_length=4096, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(default='21421421', max_length=25, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
