# Generated by Django 4.2 on 2024-11-05 02:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_contractor_commission_alter_contractor_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Указывается только для операций получения usdt от контрагента, в остальных случаях будет проигнорирован', max_digits=10, verbose_name='Курс ₪/$'),
        ),
    ]
