# Generated by Django 4.2 on 2024-08-08 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('core', '0031_userssim_circuit_api_userssim_circuit_api_collect_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_receiver', models.CharField(max_length=100, verbose_name='ФИО получателя')),
                ('phone_receiver', models.CharField(max_length=25, verbose_name='Номер телефона получателя')),
                ('items_list', models.TextField(max_length=1024, verbose_name='Предметы в посылке')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('family_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=25, verbose_name='Номер телефона отправителя')),
                ('address', models.CharField(max_length=4096, verbose_name='Адрес отправителя')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=4096, null=True, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания срока действия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер паспорта')),
                ('price', models.FloatField(default=0, verbose_name='Стоимость')),
                ('circuit_id', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Circuit id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('valid', models.BooleanField(default=True)),
                ('circuit_api', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('passport_photo_parcel', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_parcel_photo', to=settings.FILER_IMAGE_MODEL, verbose_name='Фото паспорта')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_parcels', to='core.tguser', verbose_name='Пользователь')),
                ('variation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_parcels', to='core.parcelvariation', verbose_name='Вариант посылки')),
            ],
            options={
                'verbose_name': 'посылка',
                'verbose_name_plural': 'посылки',
                'ordering': ('-created_at',),
            },
        ),
    ]
